// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

public enum TodoPriority: String, Codable, Sendable, Equatable {
    case high
    case low
    case medium
}

public enum TodoStatus: String, Codable, Sendable, Equatable {
    case active
    case archived
    case `case`
    case `default`
    case pending
}

/// Generated model for the `Todo` resource.
///
/// Every selectable field is Optional so that ad-hoc field selection is
/// safe: unselected fields decode as `nil`.
public struct Todo: Codable, Sendable, Equatable {
    public var amount: String?
    public var completed: Bool?
    public var deadline: String?
    public var `default`: String?
    public var dueAt: Date?
    public var id: String?
    public var metadata: [String: AshJSON]?
    public var priority: TodoPriority?
    public var scheduledAt: Date?
    public var score: Int?
    public var startedAt: String?
    public var status: TodoStatus?
    public var title: String?
    public var user: User?
    public var userId: String?
    public var username: String?
    public init() {}
}

public struct CreateTodoInput: Encodable, Sendable {
    public var amount: String?
    public var completed: Bool?
    public var deadline: String?
    public var `default`: String?
    public var dueAt: Date?
    public var metadata: [String: AshJSON]?
    public var priority: TodoPriority?
    public var scheduledAt: Date?
    public var score: Int?
    public var startedAt: String?
    public var status: TodoStatus?
    public var title: String
    public var userId: String?
    public var username: String?

    public init(title: String, amount: String? = nil, completed: Bool? = nil, deadline: String? = nil, `default`: String? = nil, dueAt: Date? = nil, metadata: [String: AshJSON]? = nil, priority: TodoPriority? = nil, scheduledAt: Date? = nil, score: Int? = nil, startedAt: String? = nil, status: TodoStatus? = nil, userId: String? = nil, username: String? = nil) {
        self.amount = amount
        self.completed = completed
        self.deadline = deadline
        self.`default` = `default`
        self.dueAt = dueAt
        self.metadata = metadata
        self.priority = priority
        self.scheduledAt = scheduledAt
        self.score = score
        self.startedAt = startedAt
        self.status = status
        self.title = title
        self.userId = userId
        self.username = username
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(completed, forKey: .completed)
        try container.encodeIfPresent(deadline, forKey: .deadline)
        try container.encodeIfPresent(`default`, forKey: .`default`)
        try container.encodeIfPresent(dueAt, forKey: .dueAt)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(scheduledAt, forKey: .scheduledAt)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(username, forKey: .username)
    }

    private enum CodingKeys: String, CodingKey {
        case amount
        case completed
        case deadline
        case `default`
        case dueAt
        case metadata
        case priority
        case scheduledAt
        case score
        case startedAt
        case status
        case title
        case userId
        case username
    }
}

public struct UpdateTodoInput: Encodable, Sendable {
    public var amount: String?
    public var completed: Bool?
    public var deadline: String?
    public var `default`: String?
    public var dueAt: Date?
    public var metadata: [String: AshJSON]?
    public var priority: TodoPriority?
    public var scheduledAt: Date?
    public var score: Int?
    public var startedAt: String?
    public var status: TodoStatus?
    public var title: String?
    public var userId: String?
    public var username: String?

    public init(amount: String? = nil, completed: Bool? = nil, deadline: String? = nil, `default`: String? = nil, dueAt: Date? = nil, metadata: [String: AshJSON]? = nil, priority: TodoPriority? = nil, scheduledAt: Date? = nil, score: Int? = nil, startedAt: String? = nil, status: TodoStatus? = nil, title: String? = nil, userId: String? = nil, username: String? = nil) {
        self.amount = amount
        self.completed = completed
        self.deadline = deadline
        self.`default` = `default`
        self.dueAt = dueAt
        self.metadata = metadata
        self.priority = priority
        self.scheduledAt = scheduledAt
        self.score = score
        self.startedAt = startedAt
        self.status = status
        self.title = title
        self.userId = userId
        self.username = username
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(completed, forKey: .completed)
        try container.encodeIfPresent(deadline, forKey: .deadline)
        try container.encodeIfPresent(`default`, forKey: .`default`)
        try container.encodeIfPresent(dueAt, forKey: .dueAt)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(scheduledAt, forKey: .scheduledAt)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(username, forKey: .username)
    }

    private enum CodingKeys: String, CodingKey {
        case amount
        case completed
        case deadline
        case `default`
        case dueAt
        case metadata
        case priority
        case scheduledAt
        case score
        case startedAt
        case status
        case title
        case userId
        case username
    }
}

public struct TodoFilter: Encodable, Sendable {
    public var amount: NullableComparableOperators<String>?
    public var completed: EquatableOperators<Bool>?
    public var deadline: NullableComparableOperators<String>?
    public var `default`: NullableEnumOperators<String>?
    public var dueAt: NullableComparableOperators<Date>?
    public var id: EnumOperators<String>?
    public var priority: NullableEnumOperators<TodoPriority>?
    public var scheduledAt: NullableComparableOperators<Date>?
    public var score: NullableComparableOperators<Int>?
    public var startedAt: NullableComparableOperators<String>?
    public var status: NullableEnumOperators<TodoStatus>?
    public var title: EnumOperators<String>?
    public var userId: NullableEnumOperators<String>?
    public var username: NullableEnumOperators<String>?

    public var and: [TodoFilter]?
    public var or: [TodoFilter]?
    public var not: [TodoFilter]?

    public init() {}
}

public enum TodoSortField: String, Sendable {
    case amount
    case completed
    case deadline
    case `default`
    case dueAt
    case id
    case priority
    case scheduledAt
    case score
    case startedAt
    case status
    case title
    case userId
    case username
}

public enum UserTopPriority: String, Codable, Sendable, Equatable {
    case high
    case low
    case medium
}

/// Generated model for the `User` resource.
///
/// Every selectable field is Optional so that ad-hoc field selection is
/// safe: unselected fields decode as `nil`.
public struct User: Codable, Sendable, Equatable {
    public var averageScore: Double?
    public var displayName: String?
    public var email: String?
    public var hasTodos: Bool?
    public var highestScore: Int?
    public var id: String?
    public var lowestScore: Int?
    public var name: String?
    public var todoCount: Int?
    public var todos: [Todo]?
    public var topPriority: UserTopPriority?
    public var totalScore: Int?
    public init() {}
}

public struct CreateUserInput: Encodable, Sendable {
    public var email: String
    public var name: String

    public init(email: String, name: String) {
        self.email = email
        self.name = name
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(name, forKey: .name)
    }

    private enum CodingKeys: String, CodingKey {
        case email
        case name
    }
}

public struct UserFilter: Encodable, Sendable {
    public var email: EnumOperators<String>?
    public var id: EnumOperators<String>?
    public var name: EnumOperators<String>?

    public var and: [UserFilter]?
    public var or: [UserFilter]?
    public var not: [UserFilter]?

    public init() {}
}

public enum UserSortField: String, Sendable {
    case email
    case id
    case name
}
