// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

/// Type-safe entry point for every RPC action exposed to this client.
public struct AshRpc: Sendable {
    public let client: AshRpcClient

    public init(client: AshRpcClient) {
        self.client = client
    }

    /// Calls the `create_todo` RPC action (create `Todo` record).
    public func createTodo(input: CreateTodoInput, fields: [FieldSelection] = []) async throws -> Todo {
        return try await client.execute(CreateRequest(action: "create_todo", input: input, fields: fields))
    }

    /// Calls the `destroy_todo` RPC action (destroy record).
    public func destroyTodo(id: String) async throws {
        try await client.execute(DestroyRequest(action: "destroy_todo", identity: id))
    }

    /// Calls the `find_todo` RPC action (get `Todo` record).
    public func findTodo(id: String, fields: [FieldSelection] = []) async throws -> Todo? {
        return try await client.execute(GetOptionalRequest(action: "find_todo", input: ["id": id], fields: fields))
    }

    /// Calls the `find_todo_by_title` RPC action (get `Todo` record).
    public func findTodoByTitle(title: String, fields: [FieldSelection] = []) async throws -> Todo {
        return try await client.execute(GetRequest(action: "find_todo_by_title", getBy: ["title": title], fields: fields))
    }

    /// Calls the `get_todo` RPC action (get `Todo` record).
    public func getTodo(id: String, fields: [FieldSelection] = []) async throws -> Todo {
        return try await client.execute(GetRequest(action: "get_todo", input: ["id": id], fields: fields))
    }

    /// Calls the `get_todo_by_score` RPC action (get `Todo` record).
    public func getTodoByScore(score: String, fields: [FieldSelection] = []) async throws -> Todo {
        return try await client.execute(GetRequest(action: "get_todo_by_score", input: ["score": score], fields: fields))
    }

    /// Calls the `init` RPC action (list `Todo` records).
    public func `init`(filter: TodoFilter? = nil, sort: [SortField<TodoSortField>] = [], fields: [FieldSelection] = []) async throws -> [Todo] {
        return try await client.execute(ListRequest(action: "init", filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }

    /// Calls the `list_todos` RPC action (list `Todo` records).
    public func listTodos(filter: TodoFilter? = nil, sort: [SortField<TodoSortField>] = [], fields: [FieldSelection] = []) async throws -> [Todo] {
        return try await client.execute(ListRequest(action: "list_todos", filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }

    /// Calls the `list_todos_keyset` RPC action (keyset-paginated list of `Todo` records).
    public func listTodosKeyset(page: KeysetPageParams? = nil, filter: TodoFilter? = nil, sort: [SortField<TodoSortField>] = [], fields: [FieldSelection] = []) async throws -> KeysetPage<Todo> {
        return try await client.execute(KeysetPageRequest(action: "list_todos_keyset", page: page, filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }

    /// Calls the `list_todos_no_filter` RPC action (list `Todo` records).
    public func listTodosNoFilter(sort: [SortField<TodoSortField>] = [], fields: [FieldSelection] = []) async throws -> [Todo] {
        return try await client.execute(ListRequest(action: "list_todos_no_filter", sort: ashSortString(sort), fields: fields))
    }

    /// Calls the `list_todos_no_sort` RPC action (list `Todo` records).
    public func listTodosNoSort(filter: TodoFilter? = nil, fields: [FieldSelection] = []) async throws -> [Todo] {
        return try await client.execute(ListRequest(action: "list_todos_no_sort", filter: filter.map { AnyEncodable($0) }, fields: fields))
    }

    /// Calls the `list_todos_offset` RPC action (offset-paginated list of `Todo` records).
    public func listTodosOffset(page: OffsetPageParams? = nil, filter: TodoFilter? = nil, sort: [SortField<TodoSortField>] = [], fields: [FieldSelection] = []) async throws -> OffsetPage<Todo> {
        return try await client.execute(OffsetPageRequest(action: "list_todos_offset", page: page, filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }

    /// Calls the `update_todo` RPC action (update `Todo` record).
    public func updateTodo(id: String, input: UpdateTodoInput, fields: [FieldSelection] = []) async throws -> Todo {
        return try await client.execute(UpdateRequest(action: "update_todo", identity: id, input: input, fields: fields))
    }

    /// Calls the `create_user` RPC action (create `User` record).
    public func createUser(input: CreateUserInput, fields: [FieldSelection] = []) async throws -> User {
        return try await client.execute(CreateRequest(action: "create_user", input: input, fields: fields))
    }

    /// Calls the `list_users` RPC action (list `User` records).
    public func listUsers(filter: UserFilter? = nil, sort: [SortField<UserSortField>] = [], fields: [FieldSelection] = []) async throws -> [User] {
        return try await client.execute(ListRequest(action: "list_users", filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }
}
