// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

/// Type-safe entry point for every RPC action exposed to this client.
public struct AshRpc: Sendable {
    public let client: AshRpcClient

    public init(client: AshRpcClient) {
        self.client = client
    }

    /// Calls the `list_tags` RPC action (list `Tag` records).
    public func listTags(filter: TagFilter? = nil, sort: [SortField<TagSortField>] = [], fields: [FieldSelection] = []) async throws -> [Tag] {
        return try await client.execute(ListRequest(action: "list_tags", filter: filter.map { AnyEncodable($0) }, sort: ashSortString(sort), fields: fields))
    }
}
