// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

/// Generated model for the `Category` resource.
///
/// Every selectable field is Optional so that ad-hoc field selection is
/// safe: unselected fields decode as `nil`.
public struct Category: Codable, Sendable, Equatable {
    public var id: String?
    public var name: String?
    public var publisherId: String?
    public init() {}
}

/// Generated model for the `Tag` resource.
///
/// Every selectable field is Optional so that ad-hoc field selection is
/// safe: unselected fields decode as `nil`.
public struct Tag: Codable, Sendable, Equatable {
    public var category: Category?
    public var categoryId: String?
    public var id: String?
    public var label: String?
    public init() {}
}

public struct TagFilter: Encodable, Sendable {
    public var categoryId: NullableEnumOperators<String>?
    public var id: EnumOperators<String>?
    public var label: NullableEnumOperators<String>?

    public var and: [TagFilter]?
    public var or: [TagFilter]?
    public var not: [TagFilter]?

    public init() {}
}

public enum TagSortField: String, Sendable {
    case categoryId
    case id
    case label
}
