defmodule AshSwift.Codegen do
  @moduledoc """
  Generates Swift source from a domain's reused `typescript_rpc` configuration.

  The generator is intentionally a plain module function: `build_files/1` is
  pure (domains in, `%{relative_path => source}` out) so tests can assert on the
  emitted source without touching the filesystem, and `generate/2` wraps it with
  deterministic, change-only writes.
  """

  alias AshTypescript.FieldFormatter
  alias AshTypescript.Resource.Info, as: ResourceInfo
  alias AshTypescript.Rpc.Info, as: RpcInfo

  @scalar_swift_types MapSet.new(["String", "Bool", "Int", "Double"])

  # Swift keywords that cannot appear bare as identifiers — enum case names
  # matching any of these must be backtick-escaped to produce valid Swift.
  @swift_reserved_keywords ~w(class struct enum protocol extension func var let init deinit
    return throw throws rethrows try catch defer import typealias associatedtype
    self Self super true false nil in is as any some default where)

  @types_file "AshRpcTypes.swift"
  @functions_file "AshRpcFunctions.swift"

  @header """
  // Generated by AshSwift. Do not edit by hand.
  // Regenerate with `mix ash_swift.codegen`.
  """

  @doc """
  Builds the generated Swift source for the given domains.

  Returns a map of relative file path to file contents. Pure and deterministic:
  the same domains always produce byte-identical output.

  Known limitation: no collision check between generated enum type names and
  resource struct type names. If both resolve to the same string (e.g. a resource
  named `TodoPriority` and a `priority` enum field on `Todo`), the output will
  contain two Swift types with the same name and won't compile. See issue #24.
  """
  @spec build_files([module()]) :: %{String.t() => String.t()}
  def build_files(domains) when is_list(domains) do
    primary_resources = collect_resources(domains)
    all_resources = expand_with_related(primary_resources)

    %{
      @types_file => render_types(all_resources),
      @functions_file => render_functions(primary_resources)
    }
  end

  @doc """
  Builds the files for `domains` and writes them under `output_dir`, creating it
  if needed. Writes a file only when its contents changed, so regenerating with
  no schema change produces no diff (and no mtime churn).

  Returns `{:ok, [written_relative_paths]}` where the list is sorted and
  contains only files whose contents actually changed.
  """
  @spec generate([module()], String.t()) :: {:ok, [String.t()]}
  def generate(domains, output_dir) do
    files = build_files(domains)

    written =
      files
      |> Enum.sort_by(fn {path, _} -> path end)
      |> Enum.filter(fn {path, content} ->
        write_if_changed(Path.join(output_dir, path), content)
      end)
      |> Enum.map(fn {path, _} -> path end)

    {:ok, written}
  end

  @doc """
  Returns the sorted list of relative paths whose generated content differs from
  what is currently on disk under `output_dir` (a missing file counts as
  differing). An empty list means the committed output is up to date.

  This is the staleness check behind `mix ash_swift.codegen --check`: CI can fail
  when generated Swift hasn't been regenerated after a schema change (ADR-0005).
  """
  @spec stale_files([module()], String.t()) :: [String.t()]
  def stale_files(domains, output_dir) do
    domains
    |> build_files()
    |> Enum.filter(fn {path, content} ->
      full = Path.join(output_dir, path)
      current = if File.exists?(full), do: File.read!(full), else: :none
      current != content
    end)
    |> Enum.map(fn {path, _} -> path end)
    |> Enum.sort()
  end

  # Collects every RPC-exposed resource across the given domains, normalised into
  # a sorted list of maps the renderers consume. Sorting by Swift type name keeps
  # output deterministic regardless of domain/declaration order.
  defp collect_resources(domains) do
    domains
    |> Enum.flat_map(&RpcInfo.typescript_rpc/1)
    |> Enum.map(fn %{resource: resource, rpc_actions: rpc_actions} ->
      type_name = ResourceInfo.typescript_type_name!(resource)
      {fields, enums} = collect_fields(resource, type_name)

      %{
        resource_module: resource,
        type_name: type_name,
        fields: fields,
        enums: enums,
        actions:
          rpc_actions
          |> Enum.map(fn rpc_action ->
            ash_action = Ash.Resource.Info.action(resource, rpc_action.action)

            %{
              rpc_name: rpc_action.name,
              action: rpc_action.action,
              action_type: ash_action.type,
              # get? only exists on read actions; all other types are non-get.
              is_get?: ash_action.type == :read && Map.get(ash_action, :get?, false)
            }
          end)
          |> Enum.sort_by(& &1.rpc_name)
      }
    end)
    |> Enum.sort_by(& &1.type_name)
  end

  # Returns a tuple {fields, enums} for the resource.
  #
  # fields: sorted list of %{name, swift_type} for public scalar attributes and
  # public relationships. Field names go through the same formatter AshTypescript
  # uses for output. Enum attributes produce a generated Swift enum type name
  # instead of the default "String" fallback.
  #
  # enums: sorted list of %{enum_name, cases} for each attribute whose Ash type
  # is an enum (Ash.Type.Atom with one_of constraint, or Ash.Type.Enum subtype).
  defp collect_fields(resource, type_name) do
    formatter = AshTypescript.output_field_formatter() || :camel_case

    {attr_fields, enums} =
      resource
      |> Ash.Resource.Info.public_attributes()
      |> Enum.reduce({[], []}, fn attr, {fields_acc, enums_acc} ->
        formatted_name = FieldFormatter.format_field_for_client(attr.name, resource, formatter)

        case extract_enum_cases(attr) do
          {:ok, cases} ->
            en_name = enum_type_name(type_name, formatted_name)
            field = %{name: formatted_name, swift_type: en_name}
            enum = %{enum_name: en_name, cases: cases}
            {[field | fields_acc], [enum | enums_acc]}

          :not_enum ->
            field = %{name: formatted_name, swift_type: ash_type_to_swift(attr.type)}
            {[field | fields_acc], enums_acc}
        end
      end)

    rel_fields =
      resource
      |> Ash.Resource.Info.public_relationships()
      |> Enum.flat_map(fn rel ->
        case ResourceInfo.typescript_type_name(rel.destination) do
          {:ok, dest_type} ->
            swift_type =
              case rel.cardinality do
                :one -> dest_type
                :many -> "[#{dest_type}]"
              end

            name = FieldFormatter.format_field_for_client(rel.name, resource, formatter)
            [%{name: name, swift_type: swift_type}]

          :error ->
            []
        end
      end)

    fields = (attr_fields ++ rel_fields) |> Enum.sort_by(& &1.name)
    sorted_enums = enums |> Enum.sort_by(& &1.enum_name)
    {fields, sorted_enums}
  end

  # Augments the primary resource list with any related resources referenced by
  # their relationships that aren't already in the primary set. The related
  # resource's struct must be in the types file so the nested field decodes
  # correctly. Only one hop of relationship expansion is performed for M1.
  #
  # Related entries share the same map shape as primary entries (resource_module:
  # nil, actions: []) so render_types and render_functions always see uniform
  # maps regardless of which list they iterate.
  #
  # 2-hop guard: a related resource's own relationship fields may point to types
  # that are never emitted (2 hops away). Those fields are dropped so the
  # generated Swift compiles without undefined-type references. Enum fields are
  # always safe because their type is defined in the same file.
  defp expand_with_related(primary_resources) do
    primary_type_names = MapSet.new(primary_resources, & &1.type_name)

    related_raw =
      primary_resources
      |> Enum.flat_map(fn %{resource_module: resource} ->
        resource
        |> Ash.Resource.Info.public_relationships()
        |> Enum.flat_map(fn rel ->
          case ResourceInfo.typescript_type_name(rel.destination) do
            {:ok, type_name} ->
              if MapSet.member?(primary_type_names, type_name) do
                []
              else
                {fields, enums} = collect_fields(rel.destination, type_name)
                [%{type_name: type_name, fields: fields, enums: enums}]
              end

            :error ->
              []
          end
        end)
      end)
      |> Enum.uniq_by(& &1.type_name)

    all_type_names =
      MapSet.union(primary_type_names, MapSet.new(related_raw, & &1.type_name))

    # Enum types defined in this file are always safe to reference — include
    # them in the known-type set so the 2-hop guard doesn't drop enum fields.
    # Note: `related_raw` entries use the slim %{type_name, fields, enums} shape
    # (no :resource_module or :actions keys), so only :enums is accessed here.
    all_enum_type_names =
      (primary_resources ++ related_raw)
      |> Enum.flat_map(& &1.enums)
      |> MapSet.new(& &1.enum_name)

    related =
      Enum.map(related_raw, fn %{type_name: type_name, fields: fields, enums: enums} ->
        safe_fields =
          Enum.filter(fields, fn %{swift_type: swift_type} ->
            base = swift_type |> String.replace(~r/[\[\]?]/, "")

            MapSet.member?(@scalar_swift_types, base) or
              MapSet.member?(all_type_names, base) or
              MapSet.member?(all_enum_type_names, base)
          end)

        %{
          resource_module: nil,
          type_name: type_name,
          fields: safe_fields,
          enums: enums,
          actions: []
        }
      end)

    (primary_resources ++ related) |> Enum.sort_by(& &1.type_name)
  end

  # Maps an Ash attribute type to its Swift counterpart. Enum attributes are
  # handled before this is called (via extract_enum_cases/1); this covers the
  # remaining scalar types and falls back to String for unknown types.
  defp ash_type_to_swift(Ash.Type.UUID), do: "String"
  defp ash_type_to_swift(Ash.Type.String), do: "String"
  defp ash_type_to_swift(Ash.Type.Boolean), do: "Bool"
  defp ash_type_to_swift(Ash.Type.Integer), do: "Int"
  defp ash_type_to_swift(Ash.Type.Float), do: "Double"
  defp ash_type_to_swift(_), do: "String"

  # Returns {:ok, cases} when the attribute is an enum, :not_enum otherwise.
  # Handles Ash.Type.Atom with one_of constraint and Ash.Type.Enum subtypes.
  defp extract_enum_cases(attr) do
    cond do
      attr.type == Ash.Type.Atom ->
        case Keyword.get(attr.constraints || [], :one_of) do
          values when is_list(values) and values != [] -> {:ok, values}
          _ -> :not_enum
        end

      is_atom(attr.type) and attr.type != nil and
        Code.ensure_loaded?(attr.type) and
        function_exported?(attr.type, :values, 0) and
          Ash.Type.Enum in (attr.type.module_info(:attributes)
                            |> Keyword.get_values(:behaviour)
                            |> List.flatten()) ->
        {:ok, attr.type.values()}

      true ->
        :not_enum
    end
  end

  # Computes the Swift enum type name from the resource's Swift type name and the
  # formatted field name. E.g. type_name="Todo", field_name="priority" → "TodoPriority".
  # Only the first character of field_name is uppercased; the rest is preserved so
  # camelCase field names like "deliveryStatus" → "TodoDeliveryStatus".
  defp enum_type_name(type_name, field_name) do
    capitalized =
      case field_name do
        <<first::utf8, rest::binary>> -> String.upcase(<<first::utf8>>) <> rest
        "" -> ""
      end

    type_name <> capitalized
  end

  defp render_types(resources) do
    structs =
      Enum.map_join(resources, "\n\n", fn %{type_name: type_name, fields: fields, enums: enums} ->
        enums_block =
          case enums do
            [] ->
              ""

            _ ->
              Enum.map_join(enums, "\n\n", &render_enum/1) <> "\n\n"
          end

        fields_block = render_fields(fields)

        enums_block <>
          """
          /// Generated model for the `#{type_name}` resource.
          ///
          /// Every selectable field is Optional so that ad-hoc field selection is
          /// safe: unselected fields decode as `nil`.
          public struct #{type_name}: Codable, Sendable, Equatable {
          #{fields_block}    public init() {}
          }\
          """
      end)

    IO.iodata_to_binary([@header, "\n", "import Foundation\n", body_or_empty(structs)])
  end

  defp render_fields([]), do: ""

  defp render_fields(fields) do
    fields
    |> Enum.map_join("\n", fn %{name: name, swift_type: type} ->
      "    public var #{name}: #{type}?"
    end)
    |> Kernel.<>("\n")
  end

  defp render_enum(%{enum_name: name, cases: cases}) do
    cases_block =
      cases
      |> Enum.sort_by(&to_string/1)
      |> Enum.map_join("\n", fn c ->
        str = to_string(c)
        swift_case = lower_camel(str)

        safe_name =
          if swift_case in @swift_reserved_keywords, do: "`#{swift_case}`", else: swift_case

        if swift_case == str do
          "    case #{safe_name}"
        else
          "    case #{safe_name} = \"#{str}\""
        end
      end)

    """
    public enum #{name}: String, Codable, Sendable, Equatable {
    #{cases_block}
    }\
    """
  end

  defp render_functions(resources) do
    methods =
      resources
      |> Enum.flat_map(fn %{type_name: type_name, actions: actions} ->
        Enum.map(actions, &render_method(&1, type_name))
      end)
      |> Enum.join("\n\n")

    # Indented method block, set off from the initializer by a blank line. Empty
    # when there are no actions, so the struct closes cleanly after `init`.
    methods_block = if methods == "", do: "", else: "\n\n" <> indent(methods)

    body = """
    /// Type-safe entry point for every RPC action exposed to this client.
    public struct AshRpc: Sendable {
        public let client: AshRpcClient

        public init(client: AshRpcClient) {
            self.client = client
        }#{methods_block}
    }
    """

    IO.iodata_to_binary([
      @header,
      "\n",
      "import Foundation\n",
      "import AshSwiftRuntime\n\n",
      body
    ])
  end

  # List (non-get read) actions accept a FieldSelection list and return [TypeName].
  # FieldSelection supports both scalar strings and nested relationship selections.
  defp render_method(
         %{rpc_name: rpc_name, action_type: :read, is_get?: false},
         type_name
       ) do
    func = lower_camel(rpc_name)

    """
    /// Calls the `#{rpc_name}` RPC action (list `#{type_name}` records).
    public func #{func}(fields: [FieldSelection] = []) async throws -> [#{type_name}] {
        return try await client.runList(action: "#{rpc_name}", fields: fields)
    }\
    """
  end

  # All other action types (get, create, update, destroy) keep the simple signature
  # for M1; typed inputs and returns land in later milestones.
  defp render_method(%{rpc_name: rpc_name, action: action}, type_name) do
    func = lower_camel(rpc_name)

    """
    /// Calls the `#{rpc_name}` RPC action (`#{action}` on `#{type_name}`).
    public func #{func}() async throws {
        try await client.runRaw(action: "#{rpc_name}")
    }\
    """
  end

  # ---- helpers ----

  defp body_or_empty(""), do: "\n"
  defp body_or_empty(structs), do: "\n" <> structs <> "\n"

  # Prefixes four spaces to each non-blank line of a (possibly multi-line)
  # string, leaving blank lines empty so no whitespace-only lines are emitted.
  defp indent(text) do
    text
    |> String.split("\n", trim: false)
    |> Enum.map_join("\n", fn
      "" -> ""
      line -> "    " <> line
    end)
  end

  # snake_case atom/string -> lowerCamelCase, the Swift idiom for functions and fields.
  defp lower_camel(name) do
    [first | rest] = name |> to_string() |> String.split("_", trim: true)
    Enum.join([String.downcase(first) | Enum.map(rest, &String.capitalize/1)])
  end

  defp write_if_changed(path, content) do
    current = if File.exists?(path), do: File.read!(path), else: :none

    if current == content do
      false
    else
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, content)
      true
    end
  end
end
