defmodule AshSwift.Codegen do
  @moduledoc """
  Generates Swift source from a domain's reused `typescript_rpc` configuration.

  The generator is intentionally a plain module function: `build_files/1` is
  pure (domains in, `%{relative_path => source}` out) so tests can assert on the
  emitted source without touching the filesystem, and `generate/2` wraps it with
  deterministic, change-only writes.

  M1's walking skeleton (issue #1) emits a navigable, two-file split — a types
  file and an RPC-functions file — wiring every integration layer once. Real
  field selection, typed inputs, and model fields land in later slices.
  """

  alias AshTypescript.Resource.Info, as: ResourceInfo
  alias AshTypescript.Rpc.Info, as: RpcInfo

  @types_file "AshRpcTypes.swift"
  @functions_file "AshRpcFunctions.swift"

  @header """
  // Generated by AshSwift. Do not edit by hand.
  // Regenerate with `mix ash_swift.codegen`.
  """

  @doc """
  Builds the generated Swift source for the given domains.

  Returns a map of relative file path to file contents. Pure and deterministic:
  the same domains always produce byte-identical output.
  """
  @spec build_files([module()]) :: %{String.t() => String.t()}
  def build_files(domains) when is_list(domains) do
    resources = collect_resources(domains)

    %{
      @types_file => render_types(resources),
      @functions_file => render_functions(resources)
    }
  end

  @doc """
  Builds the files for `domains` and writes them under `output_dir`, creating it
  if needed. Writes a file only when its contents changed, so regenerating with
  no schema change produces no diff (and no mtime churn).

  Returns `{:ok, [written_relative_paths]}` where the list is sorted and
  contains only files whose contents actually changed.
  """
  @spec generate([module()], String.t()) :: {:ok, [String.t()]}
  def generate(domains, output_dir) do
    files = build_files(domains)

    written =
      files
      |> Enum.sort_by(fn {path, _} -> path end)
      |> Enum.filter(fn {path, content} ->
        write_if_changed(Path.join(output_dir, path), content)
      end)
      |> Enum.map(fn {path, _} -> path end)

    {:ok, written}
  end

  @doc """
  Returns the sorted list of relative paths whose generated content differs from
  what is currently on disk under `output_dir` (a missing file counts as
  differing). An empty list means the committed output is up to date.

  This is the staleness check behind `mix ash_swift.codegen --check`: CI can fail
  when generated Swift hasn't been regenerated after a schema change (ADR-0005).
  """
  @spec stale_files([module()], String.t()) :: [String.t()]
  def stale_files(domains, output_dir) do
    domains
    |> build_files()
    |> Enum.filter(fn {path, content} ->
      full = Path.join(output_dir, path)
      current = if File.exists?(full), do: File.read!(full), else: :none
      current != content
    end)
    |> Enum.map(fn {path, _} -> path end)
    |> Enum.sort()
  end

  # Collects every RPC-exposed resource across the given domains, normalised into
  # a sorted list of maps the renderers consume. Sorting by Swift type name keeps
  # output deterministic regardless of domain/declaration order.
  defp collect_resources(domains) do
    domains
    |> Enum.flat_map(&RpcInfo.typescript_rpc/1)
    |> Enum.map(fn %{resource: resource, rpc_actions: rpc_actions} ->
      %{
        type_name: ResourceInfo.typescript_type_name!(resource),
        actions:
          rpc_actions
          |> Enum.map(fn rpc_action ->
            %{rpc_name: rpc_action.name, action: rpc_action.action}
          end)
          |> Enum.sort_by(& &1.rpc_name)
      }
    end)
    |> Enum.sort_by(& &1.type_name)
  end

  defp render_types(resources) do
    structs =
      Enum.map_join(resources, "\n\n", fn %{type_name: type_name} ->
        """
        /// Generated model for the `#{type_name}` resource.
        ///
        /// Every selectable field is Optional so that ad-hoc field selection is
        /// safe: unselected fields decode as `nil`. Fields land in a later slice.
        public struct #{type_name}: Codable, Sendable, Equatable {
            public init() {}
        }\
        """
      end)

    IO.iodata_to_binary([@header, "\n", "import Foundation\n", body_or_empty(structs)])
  end

  defp render_functions(resources) do
    methods =
      resources
      |> Enum.flat_map(fn %{type_name: type_name, actions: actions} ->
        Enum.map(actions, &render_method(&1, type_name))
      end)
      |> Enum.join("\n\n")

    # Indented method block, set off from the initializer by a blank line. Empty
    # when there are no actions, so the struct closes cleanly after `init`.
    methods_block = if methods == "", do: "", else: "\n\n" <> indent(methods)

    body = """
    /// Type-safe entry point for every RPC action exposed to this client.
    public struct AshRpc: Sendable {
        public let client: AshRpcClient

        public init(client: AshRpcClient) {
            self.client = client
        }#{methods_block}
    }
    """

    IO.iodata_to_binary([
      @header,
      "\n",
      "import Foundation\n",
      "import AshSwiftRuntime\n\n",
      body
    ])
  end

  defp render_method(%{rpc_name: rpc_name, action: action}, type_name) do
    func = lower_camel(rpc_name)

    """
    /// Calls the `#{rpc_name}` RPC action (`#{action}` on `#{type_name}`).
    public func #{func}() async throws {
        try await client.runRaw(action: "#{rpc_name}")
    }\
    """
  end

  # ---- helpers ----

  defp body_or_empty(""), do: "\n"
  defp body_or_empty(structs), do: "\n" <> structs <> "\n"

  # Prefixes four spaces to each non-blank line of a (possibly multi-line)
  # string, leaving blank lines empty so no whitespace-only lines are emitted.
  defp indent(text) do
    text
    |> String.split("\n", trim: false)
    |> Enum.map_join("\n", fn
      "" -> ""
      line -> "    " <> line
    end)
  end

  # snake_case atom/string -> lowerCamelCase, the Swift idiom for functions.
  defp lower_camel(name) do
    [first | rest] = name |> to_string() |> String.split("_", trim: true)
    Enum.join([String.downcase(first) | Enum.map(rest, &String.capitalize/1)])
  end

  defp write_if_changed(path, content) do
    current = if File.exists?(path), do: File.read!(path), else: :none

    if current == content do
      false
    else
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, content)
      true
    end
  end
end
