// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

/// Type-safe entry point for every RPC action exposed to this client.
public struct AshRpc: Sendable {
    public let client: AshRpcClient

    public init(client: AshRpcClient) {
        self.client = client
    }

    /// Calls the `list_map_onlys` RPC action (list `MapOnly` records).
    public func listMapOnlys(filter: MapOnlyFilter? = nil, fields: [FieldSelection] = []) async throws -> [MapOnly] {
        return try await client.execute(ListRequest(action: "list_map_onlys", filter: filter.map { AnyEncodable($0) }, fields: fields))
    }
}
