// Generated by AshSwift. Do not edit by hand.
// Regenerate with `mix ash_swift.codegen`.

import Foundation
import AshSwiftRuntime

/// Generated model for the `MapOnly` resource.
///
/// Every selectable field is Optional so that ad-hoc field selection is
/// safe: unselected fields decode as `nil`.
public struct MapOnly: Codable, Sendable, Equatable {
    public var metadata: [String: AshJSON]?
    public init() {}
}

public struct MapOnlyFilter: Encodable, Sendable {
    public var and: [MapOnlyFilter]?
    public var or: [MapOnlyFilter]?
    public var not: [MapOnlyFilter]?

    public init() {}
}
