defmodule AshSwift.Codegen.Emitter do
  @moduledoc """
  Renders the codegen intermediate representation (IR) to Swift source. Pure
  string work: `render_types/1` and `render_functions/1` take the plain
  resource/action/field maps produced by `AshSwift.Codegen.Reader` and return
  the contents of the two generated `.swift` files. Nothing here reads the
  manifest or calls back into the reader.
  """

  require Logger

  # Complete set of Swift reserved keywords (Swift Language Reference §Lexical Structure).
  # Enum case names matching any of these must be backtick-escaped to produce valid Swift.
  #
  # Keywords used in declarations:
  #   associatedtype class deinit enum extension fileprivate func import init inout
  #   internal let open operator precedencegroup private protocol public rethrows
  #   static struct subscript typealias var
  # Keywords used in statements:
  #   break case catch continue default defer do else fallthrough for guard if in
  #   repeat return throw throws where while
  # Keywords used in expressions and types:
  #   Any as await catch false is nil rethrows self Self super throw throws true try
  # Keywords reserved in particular contexts (pattern / context keywords):
  #   associativity convenience didSet dynamic final get indirect infix lazy left
  #   mutating none nonisolated nonmutating optional override postfix precedence
  #   prefix Protocol required right set some Type unowned weak willSet
  # Swift Concurrency keywords:
  #   actor async distributed isolated
  @swift_reserved_keywords ~w(
    associatedtype class deinit enum extension fileprivate func import init inout
    internal let open operator precedencegroup private protocol public rethrows
    static struct subscript typealias var
    break case catch continue default defer do else fallthrough for guard if in
    repeat return throw throws where while
    Any as await false is nil self Self super true try
    associativity convenience didSet dynamic final get indirect infix lazy left
    mutating none nonisolated nonmutating optional override postfix precedence
    prefix Protocol required right set some Type unowned weak willSet
    actor async distributed isolated
  )

  # The logical combinators every `{Resource}Filter` carries (issue #36). Each is
  # rendered as an optional array of the SAME filter type — the idiomatic-Swift
  # mirror of AshTypescript's `and?`/`or?`/`not?` operators. `and`/`or`/`not` are
  # the literal wire keys `Ash.Query.filter_input` consumes (confirmed live against
  # the RPC pipeline, including nested and predicate-adjacent forms): they are
  # single words, so the field formatter leaves them untouched, and none is a Swift
  # reserved keyword, so no escaping is needed. The fixed order keeps codegen
  # deterministic. The self-recursion is legal because the array indirection gives
  # the struct a fixed size.
  @filter_combinators ~w(and or not)

  @header """
  // Generated by AshSwift. Do not edit by hand.
  // Regenerate with `mix ash_swift.codegen`.
  """

  def render_types(resources) do
    structs =
      Enum.map_join(resources, "\n\n", fn resource ->
        %{
          type_name: type_name,
          fields: fields,
          enums: enums,
          input_structs: input_structs,
          sort_field: sort_field,
          filter_struct: filter_struct
        } = resource

        enums_block =
          case enums do
            [] ->
              ""

            _ ->
              Enum.map_join(enums, "\n\n", &render_enum/1) <> "\n\n"
          end

        fields_block = render_fields(fields)

        model_struct =
          enums_block <>
            """
            /// Generated model for the `#{type_name}` resource.
            ///
            /// Every selectable field is Optional so that ad-hoc field selection is
            /// safe: unselected fields decode as `nil`.
            public struct #{type_name}: Codable, Sendable, Equatable {
            #{fields_block}    public init() {}
            }\
            """

        base =
          case input_structs do
            [] ->
              model_struct

            structs ->
              input_block = Enum.map_join(structs, "\n\n", &render_input_struct/1)
              model_struct <> "\n\n" <> input_block
          end

        with_filter =
          case filter_struct do
            nil -> base
            fs -> base <> "\n\n" <> render_filter_struct(fs)
          end

        case sort_field do
          nil -> with_filter
          sf -> with_filter <> "\n\n" <> render_sort_field_enum(sf)
        end
      end)

    IO.iodata_to_binary([
      @header,
      "\n",
      "import Foundation\n",
      "import AshSwiftRuntime\n",
      body_or_empty(structs)
    ])
  end

  defp render_fields([]), do: ""

  defp render_fields(fields) do
    fields
    |> Enum.map_join("\n", fn %{name: name, swift_type: type} ->
      "    public var #{escape_swift_keyword(name)}: #{type}?"
    end)
    |> Kernel.<>("\n")
  end

  defp render_enum(%{enum_name: name, cases: cases}) do
    cases_block =
      cases
      |> Enum.sort_by(&to_string/1)
      |> Enum.map_join("\n", fn c ->
        str = to_string(c)
        swift_case = lower_camel(str)

        safe_name = escape_swift_keyword(swift_case)

        if swift_case == str do
          "    case #{safe_name}"
        else
          "    case #{safe_name} = \"#{str}\""
        end
      end)

    """
    public enum #{name}: String, Codable, Sendable, Equatable {
    #{cases_block}
    }\
    """
  end

  # Emits the typed sortable-field enum for a resource. Each case is a public
  # attribute's client-formatted (camelCase) name; the String raw value Swift
  # infers from the case name is exactly the wire field the server expects, so
  # no explicit raw values are needed. Keyword-named fields are backtick-escaped
  # (the escaped identifier still infers the unescaped raw value).
  defp render_sort_field_enum(%{type_name: name, fields: fields}) do
    cases_block =
      Enum.map_join(fields, "\n", fn field -> "    case #{escape_swift_keyword(field)}" end)

    """
    public enum #{name}: String, Sendable {
    #{cases_block}
    }\
    """
  end

  # Emits the typed {Resource}Filter struct. Each per-attribute predicate is an
  # Optional operator generic (from AshSwiftRuntime), so an unset attribute is
  # simply omitted: Swift's synthesized Encodable encodes each Optional with
  # `encodeIfPresent`, producing the `{field: {operator: value}}` map the
  # `Ash.Query.filter_input` pipeline consumes. Keyword-named fields are backtick-
  # escaped; the synthesized CodingKey still carries the unescaped wire name.
  #
  # Layout: predicate fields first, then the @filter_combinators arrays (see there
  # for the wire-key and recursion rationale), then the no-arg init. The
  # combinators are emitted even for a resource with no filterable attributes (the
  # empty clause below): the filter surface is present-but-degenerate there,
  # exactly as #35 chose to emit the empty struct rather than drop the filter
  # parameter.
  defp render_filter_struct(%{type_name: name, fields: []}) do
    """
    public struct #{name}: Encodable, Sendable {
    #{filter_combinator_props(name)}

        public init() {}
    }\
    """
  end

  defp render_filter_struct(%{type_name: name, fields: fields}) do
    props_block =
      Enum.map_join(fields, "\n", fn %{name: n, swift_type: t} ->
        "    public var #{escape_swift_keyword(n)}: #{t}?"
      end)

    """
    public struct #{name}: Encodable, Sendable {
    #{props_block}

    #{filter_combinator_props(name)}

        public init() {}
    }\
    """
  end

  # The `and`/`or`/`not` combinator property lines for a filter type, each an
  # optional array of that same type. See @filter_combinators for the wire-key
  # and recursion rationale. No `escape_swift_keyword` here: none of the three is
  # a Swift keyword, and they double as the literal wire keys — escaping would be
  # both unnecessary and (if one were a keyword) a CodingKey hazard to reason about.
  defp filter_combinator_props(name) do
    Enum.map_join(@filter_combinators, "\n", fn combinator ->
      "    public var #{combinator}: [#{name}]?"
    end)
  end

  def render_functions(resources) do
    methods =
      resources
      |> Enum.flat_map(fn %{type_name: type_name, actions: actions} ->
        Enum.flat_map(actions, fn action ->
          action |> method_specs(type_name) |> Enum.map(&render_spec/1)
        end)
      end)
      |> Enum.join("\n\n")

    # Indented method block, set off from the initializer by a blank line. Empty
    # when there are no actions, so the struct closes cleanly after `init`.
    methods_block = if methods == "", do: "", else: "\n\n" <> indent(methods)

    body = """
    /// Type-safe entry point for every RPC action exposed to this client.
    public struct AshRpc: Sendable {
        public let client: AshRpcClient

        public init(client: AshRpcClient) {
            self.client = client
        }#{methods_block}
    }
    """

    IO.iodata_to_binary([
      @header,
      "\n",
      "import Foundation\n",
      "import AshSwiftRuntime\n\n",
      body
    ])
  end

  # Renders a method spec into a Swift function. This is the single place any
  # generated function's shape is expressed — header, return clause, and the
  # `execute(SomeRequest(...))` body all live here. Per-shape variation comes in
  # as data via method_spec/2, so changing the Swift template (attributes,
  # docstring format, escaping) is a one-site edit rather than a six-clause audit.
  #
  # Spec keys:
  #   rpc_name      — the RPC action name (backtick-quoted in the docstring)
  #   func_name     — the Swift function name
  #   doc           — the parenthetical summary after "RPC action "
  #   params        — ordered [%{name, type, default}] (default nil = required)
  #   return_type   — Swift return type, or nil for a void function
  #   request_type  — the RpcRequest struct name passed to execute
  #   request_args  — ordered [{label, value}] for the request initializer
  defp render_spec(spec) do
    params_str =
      Enum.map_join(spec.params, ", ", fn
        %{name: n, type: t, default: nil} -> "#{n}: #{t}"
        %{name: n, type: t, default: d} -> "#{n}: #{t} = #{d}"
      end)

    args_str =
      Enum.map_join(spec.request_args, ", ", fn {label, value} -> "#{label}: #{value}" end)

    return_clause = if spec.return_type, do: " -> #{spec.return_type}", else: ""
    return_kw = if spec.return_type, do: "return ", else: ""

    """
    /// Calls the `#{spec.rpc_name}` RPC action (#{spec.doc}).
    public func #{escape_swift_keyword(spec.func_name)}(#{params_str}) async throws#{return_clause} {
        #{return_kw}try await client.execute(#{spec.request_type}(#{args_str}))
    }\
    """
  end

  # Expands one action into the method spec(s) render_functions emits. Most
  # actions map to a single spec. A list read with *optional* pagination maps to
  # two: the unchanged bare `[T]` spec PLUS an overloaded paginated spec whose
  # `page` argument is required. Swift resolves a `page:`-less call to the `[T]`
  # overload and a `page:`-bearing call to the paginated one — the idiomatic-Swift
  # mirror of AshTypescript's `ConditionalPaginatedResult` return type (the return
  # type is conditional on whether a page argument is supplied). See ADR-0007's
  # optional-pagination addendum.
  defp method_specs(action, type_name) do
    base = method_spec(action, type_name)

    # Always set in the action map (collect_resources); access directly so a
    # missing key fails loudly rather than silently emitting only the bare overload.
    case action.optional_pagination_type do
      :none ->
        [base]

      kind ->
        [base, optional_paginated_spec(kind, action, type_name)]
    end
  end

  # Builds the paginated *overload* spec for an optional-pagination read. Same RPC
  # action, request type, and filter/sort threading as the required-pagination
  # clauses of method_spec/2 — the one difference is the `page` argument is
  # required (default: nil ⇒ no `= …` in the signature), which is what lets Swift
  # overload resolution distinguish it from the bare `[T]` function.
  defp optional_paginated_spec(kind, %{rpc_name: rpc_name} = action, type_name) do
    {page_type, wrapper, request_type, label} =
      case kind do
        :offset -> {"OffsetPageParams", "OffsetPage", "OffsetPageRequest", "offset"}
        :keyset -> {"KeysetPageParams", "KeysetPage", "KeysetPageRequest", "keyset"}
      end

    {filter_params, filter_args} = filter_entries(action.filterable?, type_name)
    {sort_params, sort_args} = sort_entries(action.sortable?, type_name)

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "#{label}-paginated list of `#{type_name}` records",
      params:
        [%{name: "page", type: page_type, default: nil}] ++
          filter_params ++ sort_params ++ [fields_param()],
      return_type: "#{wrapper}<#{type_name}>",
      request_type: request_type,
      request_args:
        [{"action", swift_string(rpc_name)}, {"page", "page"}] ++
          filter_args ++ sort_args ++ [{"fields", "fields"}]
    }
  end

  # Classifies an action into a method spec (pure data — no Swift syntax). One
  # clause per action shape; render_spec/1 turns any of them into a function.

  # List (non-get read) actions accept a FieldSelection list. Return type and
  # the RpcRequest shape depend on the action's pagination configuration:
  #   - offset pagination → OffsetPage<TypeName> via OffsetPageRequest
  #   - keyset pagination → KeysetPage<TypeName> via KeysetPageRequest
  #   - no pagination     → [TypeName] via ListRequest
  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :read,
           is_get?: false,
           pagination_type: :offset,
           sortable?: sortable?,
           filterable?: filterable?
         },
         type_name
       ) do
    {filter_params, filter_args} = filter_entries(filterable?, type_name)
    {sort_params, sort_args} = sort_entries(sortable?, type_name)

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "offset-paginated list of `#{type_name}` records",
      params:
        [%{name: "page", type: "OffsetPageParams?", default: "nil"}] ++
          filter_params ++ sort_params ++ [fields_param()],
      return_type: "OffsetPage<#{type_name}>",
      request_type: "OffsetPageRequest",
      request_args:
        [{"action", swift_string(rpc_name)}, {"page", "page"}] ++
          filter_args ++ sort_args ++ [{"fields", "fields"}]
    }
  end

  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :read,
           is_get?: false,
           pagination_type: :keyset,
           sortable?: sortable?,
           filterable?: filterable?
         },
         type_name
       ) do
    {filter_params, filter_args} = filter_entries(filterable?, type_name)
    {sort_params, sort_args} = sort_entries(sortable?, type_name)

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "keyset-paginated list of `#{type_name}` records",
      params:
        [%{name: "page", type: "KeysetPageParams?", default: "nil"}] ++
          filter_params ++ sort_params ++ [fields_param()],
      return_type: "KeysetPage<#{type_name}>",
      request_type: "KeysetPageRequest",
      request_args:
        [{"action", swift_string(rpc_name)}, {"page", "page"}] ++
          filter_args ++ sort_args ++ [{"fields", "fields"}]
    }
  end

  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :read,
           is_get?: false,
           sortable?: sortable?,
           filterable?: filterable?
         },
         type_name
       ) do
    {filter_params, filter_args} = filter_entries(filterable?, type_name)
    {sort_params, sort_args} = sort_entries(sortable?, type_name)

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "list `#{type_name}` records",
      params: filter_params ++ sort_params ++ [fields_param()],
      return_type: "[#{type_name}]",
      request_type: "ListRequest",
      request_args:
        [{"action", swift_string(rpc_name)}] ++ filter_args ++ sort_args ++ [{"fields", "fields"}]
    }
  end

  # Get (single-record read) actions: typed lookup params and a typed return.
  # not_found_error? true → return T (throws on missing).
  # not_found_error? false → return T? (nil on missing).
  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :read,
           is_get?: true,
           get_by_params: get_by_params,
           get_by_location: location,
           not_found_error?: not_found_error?
         },
         type_name
       ) do
    dict_entries =
      Enum.map_join(get_by_params, ", ", fn %{name: n} -> ~s("#{n}": #{n}) end)

    {request_type, return_type} =
      if not_found_error?,
        do: {"GetRequest", type_name},
        else: {"GetOptionalRequest", "#{type_name}?"}

    # A pure get? carries its single primary key as the top-level `identity`
    # string (like update/destroy); native/RPC get_by fields travel as a dict
    # under `input`/`getBy`. See issue #66.
    lookup_arg =
      case location do
        :identity -> {"identity", pk_identity!(get_by_params, type_name, "get")}
        :input -> {"input", "[#{dict_entries}]"}
        :get_by -> {"getBy", "[#{dict_entries}]"}
      end

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "get `#{type_name}` record",
      params: Enum.map(get_by_params, &field_param/1) ++ [fields_param()],
      return_type: return_type,
      request_type: request_type,
      request_args: [
        {"action", swift_string(rpc_name)},
        lookup_arg,
        {"fields", "fields"}
      ]
    }
  end

  # Create actions: typed input struct + returns the created record.
  defp method_spec(
         %{rpc_name: rpc_name, action_type: :create, input_struct_name: struct_name},
         type_name
       ) do
    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "create `#{type_name}` record",
      params: [%{name: "input", type: struct_name, default: nil}, fields_param()],
      return_type: type_name,
      request_type: "CreateRequest",
      request_args: [{"action", swift_string(rpc_name)}, {"input", "input"}, {"fields", "fields"}]
    }
  end

  # Update actions: primary-key params + typed input struct + returns the updated record.
  # M1: single primary-key field only; its value travels as the `identity` string
  # in the AshTypescript RPC wire protocol (ADR-0003).
  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :update,
           input_struct_name: struct_name,
           primary_key_params: pk_params
         },
         type_name
       ) do
    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "update `#{type_name}` record",
      params:
        Enum.map(pk_params, &field_param/1) ++
          [%{name: "input", type: struct_name, default: nil}, fields_param()],
      return_type: type_name,
      request_type: "UpdateRequest",
      request_args: [
        {"action", swift_string(rpc_name)},
        {"identity", pk_identity!(pk_params, type_name, "update")},
        {"input", "input"},
        {"fields", "fields"}
      ]
    }
  end

  # Destroy actions: primary-key param only, void return.
  # M1: single primary-key field only; its value travels as the `identity` string.
  defp method_spec(
         %{rpc_name: rpc_name, action_type: :destroy, primary_key_params: pk_params},
         type_name
       ) do
    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "destroy record",
      params: Enum.map(pk_params, &field_param/1),
      return_type: nil,
      request_type: "DestroyRequest",
      request_args: [
        {"action", swift_string(rpc_name)},
        {"identity", pk_identity!(pk_params, type_name, "destroy")}
      ]
    }
  end

  # Generic (`:action`-type) actions (#54). Inputs are action arguments collected
  # into an input struct (nil when the action takes none); the return is :void or
  # {:typed, swift_type} (scalar/map — typed-record returns are skipped upstream).
  # The body is just {action, input?} — no field selection in this slice. When the
  # action takes no arguments the request's input generic has nothing to infer it
  # from, so it's pinned explicitly to the runtime's EmptyActionInput sentinel.
  defp method_spec(
         %{
           rpc_name: rpc_name,
           action_type: :action,
           input_struct_name: struct_name,
           generic_return: gen_return
         },
         _type_name
       ) do
    {params, input_args} =
      if struct_name do
        {[%{name: "input", type: struct_name, default: nil}], [{"input", "input"}]}
      else
        {[], []}
      end

    {return_type, request_type} =
      case {gen_return, struct_name} do
        # Void: I is inferred from `input:` when present, else pinned explicitly.
        {:void, nil} ->
          {nil, "VoidActionRequest<EmptyActionInput>"}

        {:void, _} ->
          {nil, "VoidActionRequest"}

        # Typed + no input: O can't infer through execute without an `input:` to
        # anchor I, so both generics are explicit.
        {{:typed, swift_type}, nil} ->
          {swift_type, "GenericActionRequest<#{swift_type}, EmptyActionInput>"}

        # Typed + input: I infers from `input:`, O from the return position through
        # execute (as create/update infer their record type).
        {{:typed, swift_type}, _} ->
          {swift_type, "GenericActionRequest"}
      end

    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "generic action",
      params: params,
      return_type: return_type,
      request_type: request_type,
      request_args: [{"action", swift_string(rpc_name)}] ++ input_args
    }
  end

  # Catch-all for any other action types not handled above.
  defp method_spec(%{rpc_name: rpc_name, action: action}, type_name) do
    %{
      rpc_name: rpc_name,
      func_name: lower_camel(rpc_name),
      doc: "`#{action}` on `#{type_name}`",
      params: [],
      return_type: nil,
      request_type: "RawRequest",
      request_args: [{"action", swift_string(rpc_name)}]
    }
  end

  # The `fields:` parameter every selectable action carries. Required (no default):
  # the RPC backend rejects an empty fields array (`empty_fields_array`), so a
  # `= []` default would compile into a call that always fails at runtime. Omitting
  # the default makes a fields-less call a compile error instead — matching
  # AshTypescript's deliberate "no select-all" field-selection design. See issue #59.
  defp fields_param, do: %{name: "fields", type: "[FieldSelection]", default: nil}

  # The optional typed `sort:` parameter and its request argument, threaded into
  # a read function when sorting is enabled. Returns `{params, request_args}` so
  # the method_spec clauses can splice them in before `fields`. When sorting is
  # disabled (enable_sort?: false), both are empty and the signature stays
  # byte-identical to the pre-sort output. The function assembles the Ash sort
  # string from the typed sort via the runtime's `ashSortString` helper.
  defp sort_entries(true, type_name) do
    {[%{name: "sort", type: "[SortField<#{type_name}SortField>]", default: "[]"}],
     [{"sort", "ashSortString(sort)"}]}
  end

  defp sort_entries(false, _type_name), do: {[], []}

  # The optional typed `filter:` parameter and its request argument, threaded into
  # a read function when filtering is enabled. Mirrors `sort_entries/2`: returns
  # `{params, request_args}` spliced in before sort. When filtering is disabled
  # (enable_filter?: false), both are empty so the signature stays byte-identical
  # to the pre-filter output. The typed `{Resource}Filter` is type-erased through
  # `AnyEncodable` so the runtime request bodies stay non-generic over the filter
  # shape; a nil filter maps to nil and is omitted from the request body.
  defp filter_entries(true, type_name) do
    {[%{name: "filter", type: "#{type_name}Filter?", default: "nil"}],
     [{"filter", "filter.map { AnyEncodable($0) }"}]}
  end

  defp filter_entries(false, _type_name), do: {[], []}

  # A lookup/primary-key field as a required Swift parameter.
  defp field_param(%{name: n, swift_type: t}), do: %{name: n, type: t, default: nil}

  # A string literal as it appears in emitted Swift source (quoted).
  defp swift_string(s), do: ~s("#{s}")

  # The primary-key field name used as the `identity` argument for update and
  # destroy. Warns on composite keys (only the first field is used until multi-PK
  # support lands) and raises when a resource has no primary key.
  defp pk_identity!(pk_params, type_name, verb) do
    case List.first(pk_params) do
      %{name: n} ->
        if length(pk_params) > 1 do
          Logger.warning(
            "AshSwift: resource #{type_name} has a composite primary key; " <>
              "#{verb} identity will only use the first field (#{n}) until multi-PK support lands."
          )
        end

        n

      nil ->
        raise "AshSwift: #{verb} codegen requires a primary key on resource #{type_name}"
    end
  end

  # ---- helpers ----

  defp body_or_empty(""), do: "\n"
  defp body_or_empty(structs), do: "\n" <> structs <> "\n"

  # Prefixes four spaces to each non-blank line of a (possibly multi-line)
  # string, leaving blank lines empty so no whitespace-only lines are emitted.
  defp indent(text) do
    text
    |> String.split("\n", trim: false)
    |> Enum.map_join("\n", fn
      "" -> ""
      line -> "    " <> line
    end)
  end

  # snake_case atom/string -> lowerCamelCase, the Swift idiom for functions and fields.
  defp lower_camel(name) do
    [first | rest] = name |> to_string() |> String.split("_", trim: true)
    Enum.join([String.downcase(first) | Enum.map(rest, &String.capitalize/1)])
  end

  # Emits a typed input struct for a create or update action. Required fields are
  # non-optional stored properties and appear first in the init. Optional fields
  # use `encodeIfPresent` so that unset fields are omitted from the JSON body
  # rather than serialised as `null` (which would tell the backend to clear them).
  defp render_input_struct(%{struct_name: name, fields: []}) do
    """
    public struct #{name}: Encodable, Sendable {
        public init() {}
    }\
    """
  end

  defp render_input_struct(%{struct_name: name, fields: fields}) do
    required = Enum.filter(fields, & &1.required?)
    optional = Enum.filter(fields, &(!&1.required?))

    props_block =
      Enum.map_join(fields, "\n", fn %{name: n, swift_type: t, required?: req?} ->
        sn = escape_swift_keyword(n)
        if req?, do: "    public var #{sn}: #{t}", else: "    public var #{sn}: #{t}?"
      end)

    init_params =
      (Enum.map(required, fn %{name: n, swift_type: t} ->
         "#{escape_swift_keyword(n)}: #{t}"
       end) ++
         Enum.map(optional, fn %{name: n, swift_type: t} ->
           "#{escape_swift_keyword(n)}: #{t}? = nil"
         end))
      |> Enum.join(", ")

    init_body =
      Enum.map_join(fields, "\n", fn %{name: n} ->
        sn = escape_swift_keyword(n)
        "        self.#{sn} = #{sn}"
      end)

    coding_keys_cases =
      Enum.map_join(fields, "\n", fn %{name: n} ->
        "        case #{escape_swift_keyword(n)}"
      end)

    encode_body =
      Enum.map_join(fields, "\n", fn %{name: n, required?: req?} ->
        sn = escape_swift_keyword(n)

        if req?,
          do: "        try container.encode(#{sn}, forKey: .#{sn})",
          else: "        try container.encodeIfPresent(#{sn}, forKey: .#{sn})"
      end)

    """
    public struct #{name}: Encodable, Sendable {
    #{props_block}

        public init(#{init_params}) {
    #{init_body}
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
    #{encode_body}
        }

        private enum CodingKeys: String, CodingKey {
    #{coding_keys_cases}
        }
    }\
    """
  end

  defp escape_swift_keyword(n) do
    if n in @swift_reserved_keywords, do: "`#{n}`", else: n
  end
end
